development:
  adapter: sqlite3
  encoding: unicode
  database: database.sqlite3
  host: localhost
  password:

production:
  adapter: postgresql
  encoding: unicode
  database: calendar_test
  pool: 5
  host: localhost
  password: